### PR TITLE
German Translation shortened

### PR DESCRIPTION
**Pull request by Gamemap**
### Translation
I shortened the translations because there were truncated (https://github.com/JohnXLivingston/peertube-plugin-livechat/pull/156#issuecomment-1432575934).
I also shortened the text for the two option buttons so they should be fixed too. I only counted the visible characters, so it would be great if you could test it.
The description of the automatic color detection had ` on the end of the line. I think it is not necessary there, so I removed it. (Please correct me if this is wrong.)

### Changelog
- Shortened Room Typ button text
- Shortened Room Typ option button text
- Shortened Share url option button text
- Removed `

### CODE REVIEW

**Comment by JohnXLivingston** [comment]
Seems good to me!

image

The ` at the end of a line was a mistake on the english version. I fixed it. Thanks.

**Comment by JohnXLivingston** [comment]
Hi @Gamemap ,

For the record, the plugin translation is now done using the Weblate software!
If you still want to help to translate the plugin, you can find more information here: https://framacolibri.org/t/plugin-livechat-translation-help-needed/18041

**Comment by Gamemap** [comment]
Hi @JohnXLivingston ,
Thank you for the information, I've updated the missing translations.
Are you planning to use Weblate for documentation translations as well?

**Comment by JohnXLivingston** [comment]
> Hi @JohnXLivingston , Thank you for the information, I've updated the missing translations. Are you planning to use Weblate for documentation translations as well?

Thanks!
Yes, i plan to use weblate for documentation. But i have to find how. It seems markdown files are not natively supported.

**Pull request merged**
