### PR TITLE
Added German translation

### PR DESCRIPTION
**Pull request by Gamemap**
I have added a german translation for :
- the plugin
- the readme file
- the documentation files

Please tell me if I should include a note in the contact section to write only in certain languages. (english, french, ...).

### CODE REVIEW

**Comment by JohnXLivingston** [comment]
Thanks a lot!

> Please tell me if I should include a note in the contact section to write only in certain languages. (english, french, ...).

I speak french and english (und ein bisschen Deutsch). Maybe you can indeed specify to write me in english or french.


For the record, the documentation will soon be entirely rewritten. I'll use github pages to host a full multilingual documentation. 
No worries, your work won't be lost :)

**Comment by JohnXLivingston** [comment]
Thanks!

**Comment by Gamemap** [comment]
I am glad that I could help you.
Unfortunately, I currently don't have a computer to run a Peertube instance, but as soon as I have one I will use your plugin.
I hope that soon it will work without external software.

**Comment by JohnXLivingston** [comment]
> I hope that soon it will work without external software.

I'm a bit stuck, because it's out of my area of expertise. But I have some leads to find someone who can help.
The problem is to download and compile Prosody and its dependencies, whatever the architecture (x86, ARM, ...) or installation type (standard, Docker, Yunohost, ...).

I'm going to release the plugin v5.6.0 with your translations. Thanks again.

**Pull request merged**
