### PR TITLE
Translations update from Framasoft Weblate

### PR DESCRIPTION
**Pull request by framabot**
Translations update from [Framasoft Weblate](https://weblate.framasoft.org) for [PeerTube LiveChat/PeerTube Plugin LiveChat](https://weblate.framasoft.org/projects/peertube-livechat/peertube-plugin-livechat/).

It also includes following components:

* [PeerTube LiveChat/Settings](https://weblate.framasoft.org/projects/peertube-livechat/settings/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by tcitworld** [comment]
Hmm, for some reason `false` is transformed into `true` by Weblate. I added the `Prefill translation with source` setting but that doesn't seem to help. :shrug: 

Is that acceptable in the current form?

**Comment by tcitworld** [comment]
Also the indentation level is configurable if that generates conflicts with other linting tools.

**Comment by JohnXLivingston** [comment]
> Hmm, for some reason `false` is transformed into `true` by Weblate. I tried the `Prefill translation with source` addon but that doesn't seem to help. shrug
> 
> Is that acceptable in the current form?

Not sure. I'll check that this afternoon.
And i will either adapt my code, or change the file format from JSON to YAML (it seems YAML files are ok).

Thanks.

**Comment by JohnXLivingston** [comment]
> Otherwise the untranslated keys can just be removed from the files (or emptied `''`) and Weblate should handle things properly.

Could be a good solution. Untranslated keys were here only for translator to know they are missing translations... This will now be handled by Weblate :)

**Comment by tcitworld** [comment]
> The repository content would be cleanest if weblate could remove untranslated strings. Can you make that change?

Unfortunately it seems the addon for this can't be activated with this configuration (source translations as keys). Weblate requires a dedicated source file to do that (like `en.yml` for instance).

**Comment by JohnXLivingston** [comment]
@tcitworld , I changed the way translations are handled in the plugin.
The commit https://github.com/JohnXLivingston/peertube-plugin-livechat/commit/89a11cd3d61915dbef1b834f4631d0c63dfc4019 merge all translation in YAML files, one per language.

We don't need 2 weblate components anymore.

There is only YAML files in the `languages` directory. One per lang. There is an english file, for reference.

In other words: we have to replace the 2 weblate components, by only one, with following parameters:

```
Motif de fichier: languages/*.yml
Fichier de langue de base mono-langue: languages/en.yml
```

I think i don't have enough rights to do it myself.
Can you do it? You can delete all current known component and translation if it is simplier for you. Thanks.

Note: i haven't documented the new process for now, i'll do it later today (or next week)

**Comment by tcitworld** [comment]
It should be done. Maybe try to change some translations to see how it goes?

**Comment by JohnXLivingston** [comment]
> It should be done. Maybe try to change some translations to see how it goes?

Okay. Just a minute.

I'm closing this PR, as it is deprecated.

**Comment by JohnXLivingston** [comment]
> It should be done. Maybe try to change some translations to see how it goes?

it works @tcitworld !
I merged this PR https://github.com/JohnXLivingston/peertube-plugin-livechat/pull/185 , and checked that the only diff in the compiled translation file is the modification i made.

Weblate also reformatted the yaml file, by cutting long lines, i wanted to check that this has no effect on the final result.


Thanks a lot for your help :)

**Pull request closed without merging**
