### PR TITLE
Translations for it.json in branch release/3.0.0

### PR DESCRIPTION
**Pull request by resoli**
Translated new strings for branch release/3.0.0

### CODE REVIEW

**Comment by JohnXLivingston** [comment]
Thanks @resoli . There is a little mistake: you have to replace «false» by the translation (in double quotes), and keep the english part.

**Comment by resoli** [comment]
Sorry, just corrected.

**Comment by JohnXLivingston** [comment]
Thanks!

**Comment by JohnXLivingston** [comment]
Hi @resoli ,

There are new strings to translate, on the `develop` branch: https://github.com/JohnXLivingston/peertube-plugin-livechat/tree/develop/languages
To see these strings in context, you can try this demo (this version isn't released yet): https://videos.john-livingston.fr/w/qqNQwFDerUB1KnFA6N6Jbi . There is a new button «share chat link» on top of the video.

**Pull request merged**
