### PR TITLE
Translations update from Framasoft Weblate

### PR DESCRIPTION
**Pull request by framabot**
Translations update from [Framasoft Weblate](https://weblate.framasoft.org) for [PeerTube LiveChat/Peertube Plugin Livechat Documentation](https://weblate.framasoft.org/projects/peertube-livechat/peertube-plugin-livechat-documentation/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Gamemap** [comment]
Hi @JohnXLivingston,
while translating into German I found two issues:
1. A spelling mistake in the word `combination` (https://weblate.framasoft.org/translate/peertube-livechat/peertube-plugin-livechat-documentation/en/?checksum=8f8dde30cf84ec2d)
2. Some of the read-only strings are missing a translation and give a warning for the same empty translation. (I think they are mostly untranslatable since they are code snippets). Maybe you could add the English string as the German translation as well. I think that some of the strings in the German language  that got a warning (not all) should also belong in the read-only section, since they are code snippets.

The German translation should be up to date with the next commit.

**Comment by JohnXLivingston** [comment]
> Hi @JohnXLivingston, while translating into German I found two issues:
> 
>     1. A spelling mistake in the word `combination` (https://weblate.framasoft.org/translate/peertube-livechat/peertube-plugin-livechat-documentation/en/?checksum=8f8dde30cf84ec2d)

Thanks! I will correct this today.

>     2. Some of the read-only strings are missing a translation and give a warning for the same empty translation. (I think they are mostly untranslatable since they are code snippets). Maybe you could add the English string as the German translation as well. I think that some of the strings in the German language  that got a warning (not all) should also belong in the read-only section, since they are code snippets.

Yes, I did not find a proper way to handle these strings.
Ideally, i should be able to filter these strings. For now, I prefer to mark them read-only, to avoid false translations. Even if it gives false warnings. 

> The German translation should be up to date with the next commit.

Thanks!

**Comment by Gamemap** [comment]
I thought some of the 12 strings with dismissed checks (in the German translation) should be also added to the read-only section. I have translated them with the original English string.

**Comment by JohnXLivingston** [comment]
Right. I marked some of them read-only.

**Pull request merged**
