### PR TITLE
Added a Japanese translation

### PR DESCRIPTION
**Pull request by fusengum**
I have added a Japanese translation for:
- the plugin
- the README file
- the documentation file(Installation Guide)

Please marge my translation if my pull request passed check by you.

### CODE REVIEW

**Comment by JohnXLivingston** [comment]
Thanks a lot!
It will be included in the upcoming v6.0.0 release.

**Comment by fusengum** [comment]
Thank you so much!
I'm looking forward to use v6.0.0 release!

**Comment by JohnXLivingston** [comment]
You can try your translations here: https://videos.john-livingston.fr/w/qqNQwFDerUB1KnFA6N6Jbi (this is an alpha release)

The v6.0.0 should be released very soon. But I have problems to make it run on ARM64 CPU (there are Peertube instance using Raspbery Pie, and I'd like it to work...).

**Comment by JohnXLivingston** [comment]
@fusengum , testing your modifications, I found a regression in Peertube v5.0.0-RC1.
I opened an issue here: https://github.com/Chocobozzz/PeerTube/issues/5445
If you are also a Peertube translator, you should check the japanese string in the Peertube translation system.

**Comment by JohnXLivingston** [comment]
@fusengum , there is a brand new documentation website for the plugin: https://johnxlivingston.github.io/peertube-plugin-livechat/

I used your japanese translations, and translated a few titles using deepL. I hope there is no mistake.

If you want to help translate missing pages you are welcome :)
Here is how to contribute to this new documentation: https://johnxlivingston.github.io/peertube-plugin-livechat/contributing/document/

**Comment by fusengum** [comment]
@JohnXLivingston 
Hi. The brand new documentation page is very nice.
I think your translations are okay but I will translate missing translation pages so I also check your translation carefully ;-)

**Comment by JohnXLivingston** [comment]
Thanks :)

**Comment by JohnXLivingston** [comment]
Hi @fusengum ,

For the record, the plugin translation is now done using the Weblate software!
If you still want to help to translate the plugin, you can find more information here: https://framacolibri.org/t/plugin-livechat-translation-help-needed/18041

**Comment by fusengum** [comment]
Hi @JohnXLivingston ,
Congratulations! I've checked your weblate repository.
I still want to help to translate the plugin, I'll translate that.

Thank you for the information!

**Comment by JohnXLivingston** [comment]
Thanks a lot @fusengum !
Your work has been merged: https://github.com/JohnXLivingston/peertube-plugin-livechat/pull/190
Will be available on the next release.

**Comment by JohnXLivingston** [comment]
hi @fusengum ,

The plugin documentation can now be translated in weblate too:
https://weblate.framasoft.org/translate/peertube-livechat/peertube-plugin-livechat-documentation
https://livingston.frama.io/peertube-plugin-livechat/fr/contributing/translate/#documentation-translation

I tried to import your previous work, but as i don't speak english, i can't check if the import is fine. So strings need to be approved in weblate.
And also, i think i lost some of them. Sorry for that, it was not easy to merge the previous work in the new process.

**Comment by fusengum** [comment]
hi @JohnXLivingston,

Thank you for inform that to me.
I'll check and translate the documentation in weblate ;-)

**Pull request merged**
