### PR TITLE
Add style compat with peertube v7

### PR DESCRIPTION
**Pull request by Chocobozzz**
## Description

Add CSS variables compat with peertube v7

## Mandatory Checks

- [x] I have added a description of the changes in the CHANGELOG files
- [x] I have run `npm run lint` to check that my changes respects the coding conventions
- [ ] I have added user documentation for the new features I added
- [ ] I have added technical documentation for the new features I added
- [ ] I added some documentation and I have run `npm run doc:translate` to generate translations files

### CODE REVIEW

**Comment by JohnXLivingston** [comment]
Thanks a lot!

I tested with 6.3.3, and saw no regression. I assume you tested with v7?

**Comment by Chocobozzz** [comment]
Yes, but I'm not 100% sure that all the intended styles are correct. You can test the plugin on https://peertube2.cpy.re/w/oBw6LwsMWWRkmXYfuYRpJd :)

**Comment by JohnXLivingston** [comment]
Seems fine.

Have you checked that there is enough contrast for Dark and Dark(brown) themes?
I find it difficult to read:
image

**Comment by JohnXLivingston** [comment]
> You're on the dark theme, not the brown one :)

Screenshot is on dark, but i tested both.



> Contrast is 4.73 for this specific case (`rgb(146, 146, 150)`/`rgb(42, 40, 39)`)

Fine :)

**Pull request merged**
