### PR TITLE
Create it.yml

### PR DESCRIPTION
**Pull request by lost-geographer**
Added Italian translation.

### CODE REVIEW

**Comment by JohnXLivingston** [comment]
There are some missing translations, that are copied from french. For example: 

```
prosody_components_label: "Activer les composants externe personnalisés Prosody"
prosody_components_description: |
  Active l'utilisation des «External XMPP components».<br>
  Cette option seule n'autorise que les connections depuis localhost.<br>
  Cette fonctionnalité peut par exemple être utilisée pour connecter des bots aux salons.

prosody_components_port_label: "Port pour les composants externe Prosody"
prosody_components_port_description: |
  Pour permettre l'utilisation de composants XMPP externes.<br>
  Cambiala se questa porta è già in uso sul tuo server.<br>
  Per ora, puoi tenere chiusa questa porta sul tuo firewall: sarà inaccessibile dall'esterno (Prosody ascolta solo il localhost).<br>
  Nota: questo potrebbe cambiare prossimamente, poiché è prevista l'aggiunta di una funzione per attivare le connessioni esterne.

```

Could you translate also translate them?

**Comment by JohnXLivingston** [comment]
If you want to see the result:

image

**Comment by JohnXLivingston** [comment]
If you don't know of to translate missing sentences, just let them empty. English will be used.

**Comment by lost-geographer** [comment]
Oups... I have those translations. I'm gonna send you the right file.

7 mar 2023 14:56:13 John Livingston ***@***.***>:

**Comment by JohnXLivingston** [comment]
deepl gave me this result. Is it ok?

```

prosody_components_label: "Abilitazione dei componenti esterni personalizzati di Prosody "
prosody_components_description: |
  Abilita l'uso di "Componenti XMPP esterni" ("External XMPP components").<br>
  Questa opzione consente solo connessioni da localhost.<br>
  Questa funzione può essere utilizzata, ad esempio, per collegare i bot alle chat room.

prosody_components_port_label: "Porta per componenti esterni Prosody"
prosody_components_port_description: |
  Per abilitare l'uso di componenti XMPP esterni.<br>
  Cambiala se questa porta è già in uso sul tuo server.<br>
  Per ora, puoi tenere chiusa questa porta sul tuo firewall: sarà inaccessibile dall'esterno (Prosody ascolta solo il localhost).<br>
  Nota: questo potrebbe cambiare prossimamente, poiché è prevista l'aggiunta di una funzione per attivare le connessioni esterne.
```

**Comment by lost-geographer** [comment]
Here you go!
```
prosody_components_label: "Abilitare le componenti esterne personalizzate di Prosody"
prosody_components_description: |
  Abilita l'uso di componenti XMPP esterne.<br>
  Questa opzione consente unicamente le connessioni dal localhost.<br>
  Questa funzione può essere utilizzata, ad esempio, per collegare i bot alle chat room.

prosody_components_port_label: "Port pour les composants externe Prosody"
prosody_components_port_description: |
  Per abilitare l'uso di componenti XMPP esterne.<br>
  Cambiala se questa porta è già in uso sul tuo server.<br>
  Per ora, puoi tenere chiusa questa porta sul tuo firewall: sarà inaccessibile dall'esterno (Prosody ascolta solo il localhost).<br>
  Nota: questo potrebbe cambiare prossimamente, poiché è prevista l'aggiunta di una funzione per attivare le connessioni esterne.
```

**Comment by JohnXLivingston** [comment]
thanks

**Pull request merged**
